branches:
 only:
  - master

language: php

php:
  - "5.5"

mysql:
  database: drupal
  username: root
  encoding: utf8

env:
 global:
  - secure: "a/9NeL71UfMqy1Ry3hpAuHIxSywF92yduXifkai34rCmCBOZzbARU6RcWG6Loriv+PnQRbwRJFdVfVJByJgRyfQ2jtLKL85pzw7ri+1WZv/7/N0EK1v0W0DAm9+f1KlVvjF7bTu3fh37jZuIrvuPUlcUnyDPuuJeLGCDOi8l3ZM="

install:

 # Create MySQL database
 - mysql -e "create database drupal;"

 # Install Drush, PHP build/test libraries, and their dependencies
 - sudo apt-get install -qq doxygen
 - pear upgrade --force pear
 - pear upgrade --force Console_GetoptPlus
 - pear upgrade-all
 - pear channel-discover pear.drush.org
 - pear channel-discover pear.phpunit.de
 - pear channel-discover pear.pdepend.org
 - pear channel-discover pear.phpqatools.org
 - pear install --alldeps drush/drush
 - pear install --alldeps pear/PHP_CodeSniffer
 - pear install --alldeps phpunit/PHPUnit_Selenium
 - pear install --alldeps pear.phpunit.de/phpcpd
 - pear install --alldeps pear.phpunit.de/phploc
 - pear install --alldeps phpqatools/PHP_CodeBrowser
 - pear install pdepend/PHP_Depend
 - phpenv rehash

 # Install Drupal coding standards so the ant build (phpcs) has access to them
 - PHP_VERSION=$(php -- < src/site/resources/codesniffer/phpversion.php)
 - CODE_SNIFFER_DIR=~/.phpenv/versions/$PHP_VERSION/pear/PHP/CodeSniffer
 - cp -r src/site/resources/codesniffer/Standards $CODE_SNIFFER_DIR
 
  # Check compliance with Drupal coding standards before building the project
 - echo 'console-results=true' > ~/.islandora-build.properties 
 - ant code_sniff
 - rm ~/.islandora-build.properties

 # Install Drupal and initialize a default site
 - drush -y dl drupal --drupal-project-rename=drupal --destination=../
 - drush -y -r ../drupal si standard --sites-subdir=default --account-name=travis --account-pass=travis --db-url=mysql://root@localhost/drupal --site-name=localhost
 - drush -y -r ../drupal cc all

 # Install islandora_ezid and enable it
 - mkdir -p ../drupal/sites/all/modules/islandora_ezid
 - cp -r * ../drupal/sites/all/modules/islandora_ezid
 - drush -y -r ../drupal en islandora_ezid

before_script:

 # Setup display for Selenium
 - export DISPLAY=:99.0
 - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
 - sleep 5

 # Start Drupal (needs to be done from drupal dir it seems(?))
 - cd ../drupal
 - drush rs --php-cgi=~/.phpenv/shims/php-cgi --server=builtin 8080 > /dev/null 2>&1 &
 - cd ../islandora_ezid
 - sleep 5

 # Start Selenium
 - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.33.0.jar
 - java -jar selenium-server-standalone-2.33.0.jar -p 4444 > /dev/null 2>&1 &
 - sleep 10

 # Configure islandora_ezid so we can run tests against it
 - php -r "print json_encode(array('ezidService'=>'https://n2t.net/ezid/','ezidNAAN'=>'99999','ezidShoulder'=>'fk4','cachedARKCount'=>'10','allowedIPs'=>'127.0.0.1','ezidUsername'=>'apitest','ezidPassword'=>'$EZIDPW','debugMode'=>TRUE));" | drush -r ../drupal vset --yes --format=json islandora_ezid_settings -
 - php -r "print json_encode(array('debugMode'=>TRUE,'labelsMode'=>TRUE,'arkExportFileName'=>'arks-','numberOfARKs'=>'5','arkTagsDefault'=>''));" | drush -r ../drupal vset --yes --format=json islandora_ezid_batch_settings -

script:

 # Run the ant build file that checks the code and builds the reports
 - ant

 # Testing
 - drush -r ../drupal core-cron
 - drush -r ../drupal php-eval "module_load_include('inc', 'islandora_ezid', 'includes/islandora_ezid.utils'); echo count_reserved_arks();"

 # Run PHPUnit to run our project's tests
 - phpunit --verbose $TRAVIS_BUILD_DIR/tests/test.php

notifications:
 email:
  recipients:
   ksclarke@gmail.com
  on_failure: change
  on_success: never
 irc:
  channels:
   "chat.freenode.net#freelibrary"
  on_failure: always
  on_success: always
